name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: ESLint annotate
        run: npx github-actions-eslint-annotator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PARTIAL_LINTING: false